version: '3.1'

services:

  mysql_db:
    image: mysql:5.7
    restart: always
    ports:
      - 3311:3306
    environment:
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

  adminer:
    image: adminer:4.7.7-standalone
    restart: always
    ports:
      - 8085:8080

volumes:
  db:

